// components/ClassGrid/data.js
export const classItems = [
  { id: 1, label: "CLASS 1", desc: "Chemical Products" },
  { id: 2, label: "CLASS 2", desc: "Paints & varnishes" },
  { id: 3, label: "CLASS 3", desc: "Cleaning & cosmetics" },
  { id: 4, label: "CLASS 4", desc: "Industrial oils" },
  { id: 5, label: "CLASS 45", desc: "Personal & social services" },
  { id: 6, label: "CLASS 1", desc: "Chemical Products" },
  { id: 7, label: "CLASS 2", desc: "Paints & varnishes" },
  { id: 8, label: "CLASS 3", desc: "Cleaning & cosmetics" },
  { id: 9, label: "CLASS 4", desc: "Industrial oils" },
  { id: 10, label: "CLASS 45", desc: "Personal & social services" },
  { id: 11, label: "CLASS 1", desc: "Chemical Products" },
  { id: 12, label: "CLASS 2", desc: "Paints & varnishes" },
  { id: 13, label: "CLASS 3", desc: "Cleaning & cosmetics" },
  { id: 14, label: "CLASS 4", desc: "Industrial oils" },
  { id: 15, label: "CLASS 45", desc: "Personal & social services" },
  { id: 16, label: "CLASS 1", desc: "Chemical Products" },
  { id: 17, label: "CLASS 2", desc: "Paints & varnishes" },
  { id: 18, label: "CLASS 3", desc: "Cleaning & cosmetics" },
  { id: 19, label: "CLASS 4", desc: "Industrial oils" },
  { id: 20, label: "CLASS 45", desc: "Personal & social services" },
  { id: 21, label: "CLASS 1", desc: "Chemical Products" },
  { id: 22, label: "CLASS 2", desc: "Paints & varnishes" },
  { id: 23, label: "CLASS 3", desc: "Cleaning & cosmetics" },
  { id: 24, label: "CLASS 4", desc: "Industrial oils" },
  { id: 25, label: "CLASS 45", desc: "Personal & social services" },
  { id: 26, label: "CLASS 1", desc: "Chemical Products" },
  { id: 27, label: "CLASS 2", desc: "Paints & varnishes" },
  { id: 28, label: "CLASS 3", desc: "Cleaning & cosmetics" },
  { id: 29, label: "CLASS 4", desc: "Industrial oils" },
  { id: 30, label: "CLASS 45", desc: "Personal & social services" },
];
